version: '3'
services:
  deepvein:
    container_name: deepvein
    ipc: host
    build:
      dockerfile: ./Dockerfile

    volumes:
      - .:/root/code

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute

