_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-arm64
act:
    value: gelu
batch_size:
    value: 32
bias:
    value: true
blocks:
    value:
        block1:
            ffn_kernel: 1
            ffn_stride: 1
            graphers: 2
            hidden: 128
            indim: 32
            kernel: 3
            knn: 9
            outdim: 64
            reduce_ratio: 4
            stride: 2
        block2:
            ffn_kernel: 1
            ffn_stride: 1
            graphers: 2
            hidden: 256
            indim: 64
            kernel: 3
            knn: 9
            outdim: 128
            reduce_ratio: 2
            stride: 2
        block3:
            ffn_kernel: 1
            ffn_stride: 1
            graphers: 6
            hidden: 512
            indim: 128
            kernel: 3
            knn: 9
            outdim: 256
            reduce_ratio: 1
            stride: 2
        block4:
            ffn_kernel: 1
            ffn_stride: 1
            graphers: 2
            hidden: 1024
            indim: 256
            kernel: 3
            knn: 9
            outdim: 512
            reduce_ratio: 1
            stride: 2
conv:
    value: mr
dataset:
    value: fv300
device:
    value: cpu
embedding_size:
    value: 512
epochs:
    value: 100
height:
    value: 224
indim_0:
    value: 3
kernel_0:
    value: 3
lr:
    value: 0.001
margin:
    value: 0.3
num_classes:
    value: 301
num_workers:
    value: 4
outdim_0:
    value: 32
scale:
    value: 64
seed:
    value: 2025
stride_0:
    value: 2
validate_after_epochs:
    value: 1
width:
    value: 224
